name: Daily Treasury Report
on:
  workflow_dispatch:
  schedule:
    - cron: '20 20 * * *'  # 4:20 PM EST (8:20 UTC)

jobs:
  generate_report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python Dependencies
        run: |
          pip install yfinance pandas yagmail pytz requests bs4 datetime unicodedata re

      - name: Download Data
        run: |
          python download_data.py
      
      - name: Run Treasury Data
        run: |
          python treasury_data.py

    
